{% set name = "zwatershed" %}
{% set version = "0.10" %}
{% set checksum = "c3a292d5bbb058cbc5c5cc908d4ec60a" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  md5: {{ checksum }}

build:
  skip: true  # [win or py3k]
  number: 0
  script: python setup.py install --single-version-externally-managed --record record.txt

requirements:
  build:
    - toolchain
    - boost 1.65.1
    - python
    - setuptools >=18.0
    - numpy 1.11.*
    - numpy >=1.7
    - cython >=0.23
    - h5py

  run:
    - boost 1.65.1
    - python
    - numpy >=1.11
    - numpy >=1.7
    - h5py

test:
  imports:
    - zwatershed

about:
  home: https://github.com/TuragaLab/zwatershed
  license: MIT
  summary: 'Code for fast watersheds.'

extra:
  recipe-maintainers:
    - csinva
