travis:
  secure:
    BINSTAR_TOKEN: HN/bRIrgVRiUvZ7e3PSIgPAPbGQ7OialGzpeSK76Bw4bOMa0bNl85c34qnxsdsMrEh6DufrCqO7Ujgh1NGEN2xsIEOuws8KMBajbv7mlkpoDR0n6YtdDCJtUKjPCE6QdGczGT1Tf3P9v++Ar/fY+4/034HUfH8ZdmgcYSPH2OMKEV9Fs7QTFi8O6iyH7ocQ8SPH4Dxx7vT0TQHDsBFEwv9TOgVCVrMdOkHy5zY9jvHJcw0VpkQk95hLhbwl8THuib0/mtbpM6cByiQaoLxrIvxxL8L3H4mrcNmQN9auRlYdxpurTzIbSo81PoIiqc2/PxeVJY050mCAAqkArjDrGeLwNOma7mCUxQrQuR9wzSh759ZP6CV8AvGJu1KcMmPSNOkE5LbD+V8PHvUC/bSyE9oro+LhoOQzFQ7ea5qKooG7uSAI9F6Z5trQzenLB5SHYnkf7eQs6uveRGIKKDs8zSBlcFNue2LZPTHuqws8SiFnzvsG2MyFan8N3C9asW/QBLBtGagKoW4hOGmm9bxPb4bd7+An5CjLC7V25EHa7jFGr8Ftcp0hv0YEUBJxFSpWTAw6ByIUgXD+FLm2/0Aivjf9qAN0NBKzZ++20WyuEDKpIFoV77Og0eEy8dG5FkJTT67B4nmNFr5bkJk7z42t8VTV9jvKEIeMuRGx4NQC1jX0=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
